In [1]:
import torch
from torch import tensor

In [2]:
import numpy as np


In [3]:
torch.__version__

'2.6.0+cpu'

In [4]:
# create a tensor with scalar value called scalar tensro
tensor0=torch.tensor(1)
tensor0

tensor(1)

In [5]:
tensor0.ndim # dim of scalar tensor is zero



0

In [6]:
list1 = [1, 2, 3, 4, 9, 2]
tensor1 = torch.tensor(list1)
tensor1

tensor([1, 2, 3, 4, 9, 2])

In [7]:
x=torch.tensor(2.0,requires_grad=True)
y=3*torch.sigmoid(x)+5
y.backward()
print(x.grad)

tensor(0.3150)


In [8]:
import numpy as np

In [9]:
A = [[1, 5], [3, 7]]
B = [[2, -1], [4, 2]]

In [10]:
np.einsum('ij, ij -> ', A, B)

np.int64(23)

## Tensors

## Creating Tensors

In [11]:
# scalar - tensor with zero dimension
tensor0 = torch.tensor(4)


In [12]:
tensor0.ndim ##Dimensions of a tensor

0

In [13]:
# vector - tensor with one dimension
tensor1 = torch.tensor([6,8,0,1,2])
tensor1.ndim
tensor1

tensor([6, 8, 0, 1, 2])

In [15]:
# matrix - tensor with two dimensions
tensor2 = torch.tensor([[0, 1, 7],[4, 2, 4]])
tensor2.ndim

2

1. No.of sqaure brackets = Dimension of tensor (.ndim or .dim)
2. To find shapoe and size of tensor we use .size or .shape method.

In [16]:
# Dimension and shape of a tensor
print(f'vector:\n{tensor1}\tNo. of dimensions: {tensor1.ndim}\tShape: {tensor1.shape}\n') ##Explains how the elements are arranged across a tensor.
print(f'matirx:\n{tensor2}\tNo. of dimensions: {tensor2.dim()}\tShape: {tensor2.size()}\n')

vector:
tensor([6, 8, 0, 1, 2])	No. of dimensions: 1	Shape: torch.Size([5])

matirx:
tensor([[0, 1, 7],
        [4, 2, 4]])	No. of dimensions: 2	Shape: torch.Size([2, 3])



In [17]:
tensor1.shape

torch.Size([5])

In [18]:
A = torch.tensor([[1,2,3],[4,5,6],[7,8,9]]) ## Looks like Numpy
A.ndim

2

In [19]:
print(tensor2.shape)
print(tensor2.size())

torch.Size([2, 3])
torch.Size([2, 3])


In [21]:
A = torch.rand((3,5))##Create a random tensor
A

tensor([[0.7279, 0.4759, 0.5482, 0.3809, 0.9556],
        [0.8351, 0.6760, 0.2090, 0.9792, 0.7595],
        [0.8598, 0.5096, 0.1874, 0.6989, 0.6948]])

In [20]:
# Alternate ways
size = (3,4)
##Uninitialized entry
tensor4 = torch.empty(size)
tensor4

tensor([[2.1707e-18, 7.0952e+22, 1.7748e+28, 1.8176e+31],
        [7.2708e+31, 5.0778e+31, 3.2608e-12, 1.7728e+28],
        [7.0367e+22, 2.1715e-18, 1.3543e-05, 2.1762e-04]])

In [22]:
#creating a random tensor which follows gaussian dist
tensor5 = torch.rand(size)
tensor5

tensor([[0.9206, 0.4676, 0.7216, 0.6656],
        [0.9369, 0.5715, 0.0468, 0.5253],
        [0.8248, 0.7878, 0.0621, 0.7851]])

In [23]:
tensor6 = torch.zeros(size)
tensor6

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
tensor7 = torch.ones(size)
tensor7

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
# Check the datatype of a tensor
tensor4 = torch.rand(6,2)
print(tensor4)
tensor4.dtype

tensor([[0.7058, 0.7276],
        [0.3616, 0.5048],
        [0.6604, 0.4357],
        [0.3016, 0.3893],
        [0.8238, 0.4459],
        [0.5004, 0.8065]])


torch.float32

In [26]:
# Create a tensor with a specific datatype within the particular range
tensor5 = torch.rand(1, 2,3, dtype=torch.float16)
print(tensor5)

tensor([[[0.8086, 0.8257, 0.9238],
         [0.3130, 0.5967, 0.6318]]], dtype=torch.float16)


In [ ]:
# Changing the datatype of a tensor
tensor4.type(torch.double)

In [27]:
## Creating tensors from a numpy array
import numpy as np

example_array = np.array([[9,3],[0,4]])
tensor8 = torch.from_numpy(example_array)##Creating tensors from the numpy.The example array and the tensor here,share the same memory.
#Any modifications in the numpy array will result in the tensor as well
tensor9 = torch.tensor(example_array)##This is not the case here.
print(example_array)
print(tensor8)
print(tensor9)
print(type(tensor9),type(tensor8))

[[9 3]
 [0 4]]
tensor([[9, 3],
        [0, 4]])
tensor([[9, 3],
        [0, 4]])
<class 'torch.Tensor'> <class 'torch.Tensor'>


In [28]:
example_array *= 2
print(example_array)
print(tensor8)
print(tensor9)

[[18  6]
 [ 0  8]]
tensor([[18,  6],
        [ 0,  8]])
tensor([[9, 3],
        [0, 4]])


In [30]:
## Creating a tensor from another tensor
tensor10 = torch.ones_like(A)
tensor10

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [29]:
# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
tensor11 = torch.ones(3,7).to(device) # "cpu","cuda"
tensor11 = torch.zeros(3,7, device=device)
device

device(type='cuda')

In [31]:
import torch
tensor23 = torch.tensor([[2,32,7],[123,23,24]])
tensor23.size()

torch.Size([2, 3])

## Accessing elements in a tensor

A = [[[5,7,2, 4],[1,2,3,4]], [[5,7,2, 4],[1,2,3,4]], [[5,7,2, 4],[1,2,3,4]] ]
A[0] 5,7,2,4
A[0][1] 7
A[1][0]

In [32]:
A = torch.tensor([[[5,7,2, 4],[1,2,3,4]], [[-5,-7,-2, -4],[-1,-2,-3,-4]], [[15,17,12, 14],[11,12,13,14]]])
A.dim()
A.shape #3,2,4  -- 2,1,3
print(A[0][1][3]) # 4
print(A[2][0][2]) #12
print(A[0][1]) # 1,2,3,4
print(A[2][1]) # 15,17,12,14
print(A[2])  # error
# print(A[1][2][3][4]) #error
print(A[0][1][2]) # 3

tensor(4)
tensor(12)
tensor([1, 2, 3, 4])
tensor([11, 12, 13, 14])
tensor([[15, 17, 12, 14],
        [11, 12, 13, 14]])
tensor(3)


In [33]:
tensor2

tensor([[0, 1, 7],
        [4, 2, 4]])

In [34]:
tensor2.dim()

2

In [35]:
tensor2.size()

torch.Size([2, 3])

In [36]:
tensor2[0]

tensor([0, 1, 7])

In [37]:
tensor2[1,0]

tensor(4)

In [38]:
# Slicing
tensor2[:, 2] # this will give us all the rows and only column 2

tensor([7, 4])

In [39]:
tensor2[0, :] # this will give us only row 0 along with all columns

tensor([0, 1, 7])

In [40]:
tensor2[:,2]

tensor([7, 4])

## Basic Tensor Operations

In [ ]:
tensor12 = torch.ones(2, 3)
tensor13 = torch.rand(2, 3)

print(tensor12)
print(tensor13)

In [ ]:
# elementwise addition
tensor14 = tensor12 + tensor13
# torch.add(tensor12,tensor13)
print(tensor14)

# elementwise subtraction
tensor15 = tensor12 - tensor13
# torch.sub(tensor12, tensor13)
print(tensor15)

# elementwise multiplication
tensor16 = tensor12 * tensor13
# torch.mul(tensor12,tensor13)
print(tensor16)

# elementwise division
tensor17 = tensor12 / tensor12
# torch.div(tensor12,tensor12)
print(tensor17)

## Manipulating a tensor

x = torch.randint('''range is specified''' 0,3,('''dimension is given here'''4,5))


x

In [ ]:
x = torch.randint(0,3,(4,5))
x

In [ ]:
#here we change the shape of the tensor
y = x.view(20)
z = x.view(-1, 10)

In [ ]:
x

In [ ]:
y

In [ ]:
z

In [ ]:
print(x.size(), y.size(), z.size())

In [ ]:
a = torch.arange(9)

In [ ]:
a

In [ ]:
#a = torch.arange(9)
a = a.reshape(3,3)
a

In [ ]:
b = torch.randint(0,9,(3,3)) ## torch.randint(low=0, high, size)
b

In [ ]:
c = torch.cat((a,b),dim=1)
c

In [ ]:
d = torch.cat((a,b),dim=0)
d

In [ ]:
a

In [ ]:
p = torch.randint(0,9,(2,3,5))
p


In [ ]:
p.sum()

In [ ]:
p.sum(dim = 0)

In [ ]:
p.sum(dim = 0).shape

In [ ]:
p

In [ ]:
p.sum(dim = 2)

In [ ]:
p.sum(dim = 1).shape

In [ ]:
p

In [ ]:
p.sum(dim = 2)

In [ ]:
p.sum(dim = 2).shape

## Autograd

Allows us to compute gradients.

$$y=3\sigma(x) + 5$$

$$\frac{\partial y}{ \partial x} = 3*\sigma(x)(1-\sigma(x))$$

$$\frac{\partial y}{ \partial x} = 3*\sigma(2)(1-\sigma(2))=3*0.8808*(1-0.8808)=0.3149$$

when we use autograd, internally there is a computational graph is being created that keeps a track of all the operations.

In [ ]:
import torch

x = torch.tensor(2.0)
x.requires_grad,x.is_leaf

In [ ]:
y = 3 * torch.sigmoid(x) + 5
y.requires_grad,y.is_leaf

In [ ]:
import torch

x = torch.tensor(2.0, requires_grad=True)

x.requires_grad, x.is_leaf

In [ ]:


y = 3 * torch.sigmoid(x) + 5
y

In [ ]:
y.requires_grad,y.is_leaf

In [ ]:
print(x.grad_fn)

In [ ]:
print(y.grad_fn)

In [ ]:
print(x.grad)
y.backward()
print(x.grad) # dy/dx

In [ ]:
x.grad.zero_()
y = 3 * torch.sigmoid(x) + 5
y.backward()
x.grad


In [ ]:
a = torch.rand(2, 5, requires_grad=True)
a

In [ ]:
b = a * a + a + 5
b

In [ ]:
c = b.mean()
c

In [ ]:
a.is_leaf,b.is_leaf,c.is_leaf

In [ ]:
b.retain_grad()

In [ ]:
print(a.grad) # Before gradient computation
c.backward()
print(a.grad) # After gradient computation #dc/da

In [ ]:
b.grad

### Gradient Descent

In [ ]:
# Generate train data # y = 5 * x + 3
x = torch.linspace(-1.0,1.0,15).reshape(15,1)
w = torch.tensor([5])
b = torch.tensor([3])
y = w * x + b
print(x.shape)

In [ ]:
print(x)# Parameter initialization
w = torch.randn(size=(1,1), requires_grad=True)
b = torch.randn(size=(1,1), requires_grad=True)
print(x+b)

In [ ]:
# no require_grad =True
# x without gradient tracking
#x = torch.randn(size=(1,1))  # No requires_grad=True

# Initialize parameters WITHOUT gradient tracking
w = torch.randn(size=(1,1))  # No requires_grad=True
b = torch.randn(size=(1,1))  # No requires_grad=True

print(x)
print(w)
print(b)

# Perform an operation
y = x + b
print(y)


In [ ]:
def forward(x):
    return w * x + b

def loss(y, y_pred):
    return ((y_pred - y)**2).mean()

print('w:',w)
print('b:',b)

In [ ]:
# Define hyperparameters
learning_rate = 0.03
num_epochs = 180

# Train the model
for epoch in range(num_epochs):
    y_pred = forward(x)

    l = loss(y, y_pred)

    l.backward()

    with torch.no_grad():
      w -= learning_rate * w.grad
      b -= learning_rate * b.grad

    w.grad.zero_()
    b.grad.zero_()


    if (epoch+1) % 10 == 0:
        print(f'epoch {epoch+1}: w = {w.item():.3f}, b = {b.item():.3f},loss = {l.item():.3f}')

## Neural Networks

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

from torchvision import datasets,transforms

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [ ]:
print(dir(datasets))

In [ ]:
## Hyper-parameters
hidden_size = 400 #number of neurons in hidden layer
num_epochs = 8
batch_size = 32
learning_rate = 0.0001

In [ ]:
## Load the MNIST dataset
train_dataset = datasets.CIFAR100(root='./data', train=True, download=True, transform=transforms.ToTensor())
test_dataset = datasets.CIFAR100(root='./data', train=False, download=True, transform=transforms.ToTensor())

In [ ]:
## Training Data
#print(train_dataset)
print(train_dataset.classes)
print(train_dataset.data.shape)



In [ ]:
## Test Data
print(test_dataset.classes)
print(test_dataset.data.shape)
print(test_dataset.targets)

In [ ]:
in_features = 3072 # Input size - 28 x 28 we'll flatten this 28 * 28
out_features = 100 # no. of classes

In [ ]:
train_dataloader = torch.utils.data.DataLoader(dataset=train_dataset, batch_size = batch_size, shuffle=True)

test_dataloader = torch.utils.data.DataLoader(dataset=test_dataset, batch_size = batch_size, shuffle=False)

In [ ]:
import matplotlib.pyplot as plt

data = iter(train_dataloader)
imgs,labels = next(data)
print(imgs.shape)
print(labels.shape)

for i in range(20):
    plt.subplot(4,5,i+1)
    plt.imshow(imgs[i].permute(1, 2, 0))
    plt.xlabel(f'Label = {labels[i].item()}')
plt.show()

In [ ]:
class BasicNeuralNet(nn.Module):
  #define constructor which is the skeleton of nn
    def __init__(self,hidden_size):
      #call the constructor of te base class
        super(BasicNeuralNet, self).__init__()
        self.hidden_size = hidden_size
        self.layer1 = nn.Linear(in_features, self.hidden_size)
        self.layer2 = nn.Linear(self.hidden_size, out_features)

    def forward(self, x):
      #here x is the input
        out = self.layer1(x)
        out = torch.relu(out)
        out = self.layer2(out)
        #problem is multiclass classification so for this we will use cross entropy loss
        return out

model = BasicNeuralNet(hidden_size).to(device)

In [ ]:
w1,b1,w2,b2 = list(model.parameters())

In [ ]:
# First linear layer
# print(w1,b1)
print(w1.shape) #(out_features,in_feat
print(b1.shape)

In [ ]:
# Second linear layer
# print(w2,b2)
# print(w2.shape)
# print(b2.shape)

In [ ]:
criterion = nn.CrossEntropyLoss() # Loss
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

In [ ]:
# Training
total_steps = len(train_dataloader)
for epoch in range(num_epochs):
    for i, (images, labels) in enumerate(train_dataloader):
        images = images.reshape(-1, 32*32*3).to(device)
        labels = labels.to(device)

        # Forward pass
        outputs = model(images)

        loss = criterion(outputs, labels)

        # Backpropagation
        loss.backward()

        optimizer.step() # Parameter update
        optimizer.zero_grad()

        if i % 300 == 0:
            print (f'Epoch {epoch}, Step {i}/{total_steps}, Loss: {loss.item():.3f}')

In [ ]:
# Test the model
with torch.no_grad():
    correct = 0
    num_samples = len(test_dataloader.dataset)

    for imgs, labels in test_dataloader:
        imgs = imgs.reshape(-1, 32*32*3).to(device)

        labels = labels.to(device)

        outputs = model(imgs)

        _, predicted = torch.max(outputs, 1)
        correct += (predicted == labels).sum().item()


    acc = correct / num_samples
    print(f'Accuracy: {100*acc} %')